from setuptools import setup, find_packages

setup(
    name="perspective2d",
    version="0.1",
    packages=find_packages(),
    install_requires=[
        'detectron2@git+https://github.com/facebookresearch/detectron2.git@4e447553eb32b6e3784df0b8fca286935107b2fd',
        "torchvision",
        "torchaudio",
        "openexr",
        "gitpython",
        "opencv-contrib-python",
        "albumentations",
        "pyequilib==0.3.0",
        "skylibs",
        "timm",
        "mmcv",
        "h5py",
        "tensorboard",
        "setuptools==59.5.0",
        "gradio",
    ],
    author="Linyi Jin",
    author_email="jinlinyi@umich.edu",
    description="Code for CVPR 2023 Perspective Fields for Single Image Camera Calibration",
    long_description=open("README.md").read(),
    long_description_content_type="text/markdown",
    url="https://github.com/jinlinyi/PerspectiveFields",
    classifiers=[
        "Development Status :: 3 - Alpha",
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.9",
    ],
)
